spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/zeebe
    username: root
    password: 123456
  data:
    r2dbc:
      repositories:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
